#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 21, 2019 01:38:40 AM -03  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import rufomo3fetcher_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    rufomo3fetcher_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    rufomo3fetcher_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font16 = "-family {DejaVu Sans} -size 8 -weight normal -slant "  \
            "italic -underline 0 -overstrike 0"

        top.geometry("600x233+378+217")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1, 1)
        top.title("Rufo MP3 Fetcher")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.383, rely=0.601, height=31, width=98)
        self.Button1.configure(text='''Download!''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.383, rely=0.258,height=23, relwidth=0.56)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.383, rely=0.429,height=23, relwidth=0.56)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.167, rely=0.258, height=21, width=116)
        self.Label1.configure(text='''Insert Video URL:''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.017, rely=0.429, height=21, width=216)
        self.Label2.configure(text='''Enter Subfolder name (optional):''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.75, rely=0.901, height=17, width=133)
        self.Label3.configure(font=font16)
        self.Label3.configure(text='''Author: Matias Garafoni''')

if __name__ == '__main__':
    vp_start_gui()





